In [1]:
import tensorflow as tf

# === THESE LINES MUST BE AT THE VERY TOP, BEFORE ANY OTHER TF USAGE ===
tf.config.optimizer.set_jit(False) # Disable XLA
# For debugging, let's explicitly print if JIT is enabled
print(f"tf.config.optimizer.get_jit() is: {tf.config.optimizer.get_jit()}")

tf.config.threading.set_inter_op_parallelism_threads(0)
tf.config.threading.set_intra_op_parallelism_threads(0)

tf.get_logger().setLevel('ERROR')

print("TensorFlow version:", tf.__version__)
print("Built with CUDA:", tf.test.is_built_with_cuda())
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))
print("List of physical GPUs:", tf.config.list_physical_devices('GPU'))

2025-06-25 23:13:22.353407: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-25 23:13:22.368116: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1750889602.381984  297175 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1750889602.386742  297175 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1750889602.400032  297175 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1750889602.400064  297175 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1750889602.400065  297175 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1750889602.400066  297175 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-06-25 23:13:22.405001: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

tf.config.optimizer.get_jit() is:
TensorFlow version: 2.19.0
Built with CUDA: True
Num GPUs Available: 1
List of physical GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
from tensorflow.keras import mixed_precision
from tensorflow.keras.mixed_precision import LossScaleOptimizer

# Set global mixed precision policy
mixed_precision.set_global_policy('float32')

# Optional: check and confirm
policy = mixed_precision.global_policy()

print("Compute dtype:", policy.compute_dtype)
print("Variable dtype:", policy.variable_dtype)

Compute dtype: float32
Variable dtype: float32

In [3]:
from tensorflow.keras import backend as K
from tensorflow.keras.optimizers import Adam

from sklearn.model_selection import KFold

In [4]:
import os
import numpy as np
import pandas as pd

os.environ['TF_GPU_ALLOCATOR'] = 'cuda_malloc_async'
os.environ['TF_XLA_FLAGS'] = '--tf_xla_auto_jit=off'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

In [5]:
import Components.image_utils as image_utils
from Components.segmentation_utils import Losses, Metrics

In [6]:
from Components.unet_models import ModifiedUNet, DoubleUNet
from Components.model_optimisers import HnAdam

In [7]:
from Components.definitions import *

print(f"Dataset path: {DATA_ROOT}")
print(f"Meta path: {Paths.metadata_csv}")
print(f"Mass training data path: {Paths.new_mass_train_csv}")
print(f"Mass test data path: {Paths.new_mass_test_csv}")
print(f"Mass train tensor path: {Paths.mass_train_tensor_dir}")
print(f"Mass test tensor path: {Paths.mass_test_tensor_dir}")

Dataset path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688
Meta path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/metadata.csv
Mass training data path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/new_mass_case_description_train_set.csv
Mass test data path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/new_mass_case_description_test_set.csv
Mass train tensor path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/mass_tensor/train
Mass test tensor path: /mnt/c/Users/lejam/Desktop/CBIS-DDSM/manifest-1748122768688/mass_tensor/test

# Data Processing

In [8]:
# Load updated mass datasets
new_mass_train = pd.read_csv(Paths.new_mass_train_csv)
new_mass_test = pd.read_csv(Paths.new_mass_test_csv)

In [9]:
print(new_mass_train.shape)
new_mass_train.head(2)

(1318, 14)

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path
0,P_00001,3,LEFT,CC,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...,Mass-Training_P_00001_LEFT_CC_1/1.3.6.1.4.1.95...
1,P_00001,3,LEFT,MLO,1,mass,IRREGULAR-ARCHITECTURAL_DISTORTION,SPICULATED,4,MALIGNANT,4,Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...,Mass-Training_P_00001_LEFT_MLO_1/1.3.6.1.4.1.9...

In [10]:
print(new_mass_test.shape)
new_mass_test.head(2)

(378, 14)

,patient_id,breast_density,left or right breast,image view,abnormality id,abnormality type,mass shape,mass margins,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path
0,P_00016,4,LEFT,CC,1,mass,IRREGULAR,SPICULATED,5,MALIGNANT,5,Mass-Test_P_00016_LEFT_CC/1.3.6.1.4.1.9590.100...,Mass-Test_P_00016_LEFT_CC_1/1.3.6.1.4.1.9590.1...,Mass-Test_P_00016_LEFT_CC_1/1.3.6.1.4.1.9590.1...
1,P_00016,4,LEFT,MLO,1,mass,IRREGULAR,SPICULATED,5,MALIGNANT,5,Mass-Test_P_00016_LEFT_MLO/1.3.6.1.4.1.9590.10...,Mass-Test_P_00016_LEFT_MLO_1/1.3.6.1.4.1.9590....,Mass-Test_P_00016_LEFT_MLO_1/1.3.6.1.4.1.9590....

### Use **Laplacian filters** and prepare the datasets in tensor format

In [11]:
process_train = False
process_test = False

target_train_rows = new_mass_train.shape[0]
target_test_rows = new_mass_test.shape[0]
target_mass_train = new_mass_train[: target_train_rows]
target_mass_test = new_mass_test[: target_test_rows]

In [12]:
train_images = None
if process_train:
    train_images = tf.data.Dataset.from_tensor_slices((
        list(map(lambda x: image_utils.load_image(os.path.join(data_root,'CBIS-DDSM', x), TARGET_SIZE[:2]), target_mass_train['image file path'])),
        list(map(lambda x: image_utils.mask_image(os.path.join(data_root,'CBIS-DDSM', x), TARGET_SIZE[:2]), target_mass_train['ROI mask file path']))
    ))
    tf.data.Dataset.save(train_images, Paths.mass_train_tensor_dir)
else:
    train_images = tf.data.Dataset.load(Paths.mass_train_tensor_dir)
for x, y in train_images.take(1):
    print(f"train image shape: {x.shape}, {y.shape}")

train image shape: (128, 128, 3), (128, 128, 1)

I0000 00:00:1750889608.627780  297175 gpu_process_state.cc:208] Using CUDA malloc Async allocator for GPU: 0
I0000 00:00:1750889608.628030  297175 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5564 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070 Ti Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
2025-06-25 23:13:28.756942: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

In [13]:
test_images = None
if process_test:
    test_images = tf.data.Dataset.from_tensor_slices((
        list(map(lambda x: image_utils.load_image(os.path.join(data_root,'CBIS-DDSM', x), TARGET_SIZE[:2]), target_mass_test['image file path'])),
        list(map(lambda x: image_utils.mask_image(os.path.join(data_root,'CBIS-DDSM', x), TARGET_SIZE[:2]), target_mass_test['ROI mask file path']))
    ))
    #torch.save(test_images, mass_test_tensor_path)
    tf.data.Dataset.save(test_images, Paths.mass_test_tensor_dir)
else:
    #test_images = torch.load(mass_test_tensor_path)
    test_images = tf.data.Dataset.load(Paths.mass_test_tensor_dir)
for x, y in test_images.take(1):
    print(f"test image shape: {x.shape}, {y.shape}")

test image shape: (128, 128, 3), (128, 128, 1)

2025-06-25 23:13:28.858344: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

In [14]:
combined_dataset = train_images.concatenate(test_images)
for x, y in combined_dataset.take(1):
    print(f"combined image shape: {x.shape}, {y.shape}")

combined image shape: (128, 128, 3), (128, 128, 1)

### Create training, validation, and test datasets

In [15]:
train_rows = len(train_images)
test_rows = len(test_images)
val_size = int(0.8 * test_rows)
test_size = test_rows - val_size
print(f"Number of train_images: {train_rows}")
print(f"Number of test_images: {test_rows}")
print(f"Validation data size: {val_size}")
print(f"Test batch size: {test_size}")

BATCH_SIZE = 8
print(f"batch size: {BATCH_SIZE}")

Number of train_images: 1318
Number of test_images: 378
Validation data size: 302
Test batch size: 76
batch size: 8

In [16]:
# Train dataset
train_batches = (
    train_images
    .cache() # Cache in memory for performance
    .shuffle(buffer_size=train_rows)  # Shuffle the full dataset
    .batch(BATCH_SIZE)
    .map(image_utils.Augment())
    .repeat() # Repeat indefinitely for training
    .prefetch(tf.data.AUTOTUNE) # Prefetch for optimal GPU/CPU usage
)

# Validation and Test datasets
validation_batches = (
    test_images
    .take(val_size)
    .batch(BATCH_SIZE, drop_remainder=True)
)

test_batches = (
    test_images
    .skip(val_size)
    .take(test_size)
    .batch(BATCH_SIZE)
)

# Model Training

In [17]:
model = ModifiedUNet(input_shape=TARGET_SIZE)
#model = DoubleUNet(input_shape=TARGET_SIZE)

In [18]:
opt = LossScaleOptimizer(HnAdam(learning_rate=1e-4))
#opt = tf.keras.optimizers.Adam(learning_rate=1e-5)

model.compile(
    optimizer=opt,
    loss=Losses.combined_loss, # focal_tversky_loss, #combined_loss, # bce_dice_loss, # Loss function to minimise
    metrics=["accuracy", Metrics.dice_coef, Metrics.jaccard_index],
    jit_compile=False
) # List of metrics to m

In [19]:
# Stop training when a monitored metric has stopped improving
earlystop = tf.keras.callbacks.EarlyStopping(
    monitor=['val_dice_coef', 'val_jaccard_index'],
    patience=10, # Number of epochs with no improvement after which training will be stopped.
    verbose=1, # Mode 1 displays messages when the callback takes an action.
    restore_best_weights=True
)

# Reduce learning rate when a metric has stopped improving
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor=['val_dice_coef', 'val_jaccard_index'],
    factor=0.9, # Factor by which the learning rate will be reduced. new_lr = lr * factor
    patience=3, # Number of epochs with no improvement after which learning rate will be reduced.
    verbose=1, # 1: update messages.
    mode='max', # In 'max' mode it will be reduced when the quantity monitored has stopped increasing.
    min_lr=1e-4 # Lower bound on the learning rate.
)

callbacks=[earlystop, reduce_lr]
#callbacks=[]

In [20]:
NUM_EPOCHS = 20
ITER_EPOCHS = 5
K_SPLIT = 10

STEPS_PER_EPOCH = train_rows // BATCH_SIZE
VALIDATION_STEPS = val_size // BATCH_SIZE

print(f"steps per epoch: {STEPS_PER_EPOCH}")
print(f"validation steps: {VALIDATION_STEPS}")

steps per epoch: 164
validation steps: 37

In [21]:
history = []

# Convert the dataset to a list (or NumPy if small enough)
data_list = list(combined_dataset)
X_all = np.array([x[0].numpy() for x in data_list])
Y_all = np.array([x[1].numpy() for x in data_list])

kf = KFold(n_splits=K_SPLIT, shuffle=True, random_state=42)
dice_scores = []

for n in range(ITER_EPOCHS):
    for train_idx, val_idx in kf.split(X_all):
        # Slice the data using indices
        X_train, Y_train = X_all[train_idx], Y_all[train_idx]
        X_val, Y_val = X_all[val_idx], Y_all[val_idx]
    
        # Convert back to tf.data.Dataset
        train_ds = tf.data.Dataset.from_tensor_slices((X_train, Y_train)).batch(8).repeat()
        val_ds = tf.data.Dataset.from_tensor_slices((X_val, Y_val)).batch(8).repeat()
    
        hist = model.fit(
            train_ds,
            validation_data=val_ds,
            epochs=NUM_EPOCHS,
            steps_per_epoch=STEPS_PER_EPOCH,
            validation_steps=VALIDATION_STEPS,
            callbacks=callbacks
        )

        history.append(hist)
        
        results = model.evaluate(val_ds, steps=VALIDATION_STEPS)
        dice_scores.append(results[2])

        K.clear_session()

        print(f"Dice score: {results[2]:.4f}, Mean: {np.mean(dice_scores):.4f}")

2025-06-25 23:13:34.901458: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

Epoch 1/20

I0000 00:00:1750889621.781539  300113 cuda_dnn.cc:529] Loaded cuDNN version 91002

  6/164 ━━━━━━━━━━━━━━━━━━━━ 17s 110ms/step - accuracy: 0.6704 - dice_coef: 9.8333e-04 - jaccard_index: 4.9214e-04 - loss: 0.8196

KeyboardInterrupt:

### Save model

In [ ]:
# Save the entire model
model.save(os.path.join(data_root, 'mass_model.keras'))

### Save history

In [ ]:
# Convert to DataFrame
#hist_df = pd.DataFrame(history.history)
all_histories = []

for i, hist in enumerate(history):
    df = pd.DataFrame(hist.history)
    df['fold'] = i  # optional, to mark which fold this history belongs to
    all_histories.append(df)

# Combine all fold histories into one DataFrame
hist_df = pd.concat(all_histories, ignore_index=True)

# Save to CSV
hist_df.to_csv(os.path.join(data_root, 'history.csv'), index=False)